version: '3'

services:
  server:
    container_name: casmm-server-dev
    image: strapi/strapi
    environment: 
      - DATABASE_HOST=db
    ports:
      - 1337:1337
    volumes:
      - ./server:/srv/app
    depends_on:
      - db
  compile:
    container_name: casmm-compile-dev
    build: ./compile
    restart: always
    ports:
      - 8080:8080
  db:
    container_name: casmm-db-dev
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENVIRONMENT: development
      DATABASE_URL: strapi
      SCRIPT_PATH: /docker-entrypoint-initdb.d