name: Deploy Production
on:
  release:
    types: [ published ]
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Built, test, and deploy app
        run: ./scripts/build_test_deploy.sh
        env:
          IMAGE_NAME: server
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
          APP_NAME: casmm
          APP_TYPE: web
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}