name: Deploy Production
on:
  release:
    types: [ published ]
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Built, test, and deploy app
        uses: STEM-C/auto/build-test-deploy@develop
        with:
          image_name: server
          image_tag: ${{ steps.get_version.outputs.VERSION }}
          app_name: casmm
          app_type: web
          github_token: ${{ secrets.GITHUB_TOKEN }}
          heroku_token: ${{ secrets.HEROKU_TOKEN }}