name: Update Review App
on: 
  pull_request:
    branches: [ develop ]
    types: [ synchronize ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get review app name
        id: get_name
        run: echo ::set-output name=NAME::review-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      - name: Built, test, and deploy app
        run: ./scripts/build_test_deploy.sh
        env:
          IMAGE_NAME: server
          IMAGE_TAG: ${{ steps.get_name.outputs.NAME }}
          APP_NAME: ${{ steps.get_name.outputs.NAME }}
          APP_TYPE: web
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}